# Generated by Django 3.2.13 on 2022-04-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
